### ISSUE TITLE
Error: Can't resolve './bus' 

### ISSUE THREAD

**Issue by vaughanwatson** [Botre/vue-connection-listener#1]
Error is produced when trying to compile Vue app.

This is because of the following code:
import bus from './bus'; // Event bus instance

There are no Docs to  explain what should go in the bus.js file and where in the app file structure it should be placed.

Should there be an example bus.js as part of the package?

**Comment by botre** [comment]
Hello,

 You need to import **your own** event bus and then inject it as a dependency.

Creating a bus could be as simple as creating a bus.js file with the following contents:

```
import Vue from 'vue';
export default new Vue();
```

For more info:

https://alligator.io/vuejs/global-event-bus/

I will add this clarification to the project documentation 👍

**Comment by vaughanwatson** [comment]
Great stuff:

Others might find this useful too.
[https://medium.com/@andrejsabrickis/https-medium-com-andrejsabrickis-create-simple-eventbus-to-communicate-between-vue-js-components-cdc11cd59860](https://medium.com/@andrejsabrickis/https-medium-com-andrejsabrickis-create-simple-eventbus-to-communicate-between-vue-js-components-cdc11cd59860)
